import type { Metadata } from 'next';
import { Inter, Noto_Sans_Thai } from 'next/font/google';
import './globals.css';
import HeaderView from '@/components/header.component';
import Image from 'next/image';
import DrawerView from '@/components/drawer.component';
import { Card } from '@nextui-org/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ware House Management',
  description: 'Generated by create next app',
};

const notoSans = Noto_Sans_Thai({
  subsets: ['thai', 'latin'],
  display: 'swap',
  variable: '--font-sans-thai',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${notoSans.variable} light`}>
      <body className="grid grid-cols-6 gap-x-2 ">
        <HeaderView />
        <DrawerView />

        {/* <Card className="col-span-5 ... overflow-y-scroll mr-5 shadow-none bg-gray-100" style={{height: "900px"}}>{children}</Card> */}
        <div className="bg-gray-100 mr-5 rounded-2xl col-span-5 ..." style={{height: "900px"}}>{children}</div>
      </body>
    </html>
  );
}
