const columns = [
  {
    key: 'id',
    label: 'NO.',
  },

  {
    key: 'image',
    label: 'Image',
  },
  {
    key: 'barcode',
    label: 'Barcode',
  },
  {
    key: 'bookNo',
    label: 'Book NO.',
  },
  {
    key: 'bookName',
    label: 'Name',
  },
  {
    key: 'quantity',
    label: 'Quantity',
  },

  {
    key: 'status',
    label: 'Status',
  },
  {
    key: 'createAt',
    label: 'Create At',
  },
  {
    key: 'updateAt',
    label: 'Update At',
  },
  {
    key: 'deleteAt',
    label: 'Delete At',
  },
  {
    key: 'actions',
    label: 'Actions',
  },
];

const statusOptions = [
  {key: "Active", uid: "Active"},
  {key: "Paused", uid: "Paused"},
  {key: "Vacation", uid: "Vacation"},
];

export const product = [
  {
    id: '1',
    image: 'N/A',
    barcode: 'Barcode-001',
    bookNo: 'B0101-V01',
    bookName: 'ฟิสิกส์เพื่อสอบเข้าเตรียมอุดมฯ1',
    quantity: '5',
    status: 'Paused',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },
  {
    id: '2',
    image: 'N/A',
    barcode: 'Barcode-002',
    bookNo: 'B0102-V01',
    bookName: 'ฟิสิกส์เพื่อสอบเข้าเตรียมอุดมฯ2',
    quantity: '10',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },
  {
    id: '3',
    image: 'N/A',
    barcode: 'Barcode-003',
    bookNo: 'B0103-V01',
    bookName: 'สรุปเนื้อหาละเอียด ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },
  {
    id: '4',
    image: 'N/A',
    barcode: 'Barcode-004',
    bookNo: 'B0104-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Vacation',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },
  {
    id: '5',
    image: 'N/A',
    barcode: 'Barcode-005',
    bookNo: 'B0105-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '6',
    image: 'N/A',
    barcode: 'Barcode-006',
    bookNo: 'B0106-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '7',
    image: 'N/A',
    barcode: 'Barcode-007',
    bookNo: 'B0107-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Vacation',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '8',
    image: 'N/A',
    barcode: 'Barcode-008',
    bookNo: 'B0108-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Vacation',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '9',
    image: 'N/A',
    barcode: 'Barcode-009',
    bookNo: 'B0109-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Vacation',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '10',
    image: 'N/A',
    barcode: 'Barcode-010',
    bookNo: 'B0110-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '11',
    image: 'N/A',
    barcode: 'Barcode-011',
    bookNo: 'B0111-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '12',
    image: 'N/A',
    barcode: 'Barcode-012',
    bookNo: 'B0112-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '13',
    image: 'N/A',
    barcode: 'Barcode-013',
    bookNo: 'B0113-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '14',
    image: 'N/A',
    barcode: 'Barcode-014',
    bookNo: 'B0114-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Paused',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },
  {
    id: '15',
    image: 'N/A',
    barcode: 'Barcode-015',
    bookNo: 'B0115-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '16',
    image: 'N/A',
    barcode: 'Barcode-016',
    bookNo: 'B0116-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '17',
    image: 'N/A',
    barcode: 'Barcode-017',
    bookNo: 'B0117-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '18',
    image: 'N/A',
    barcode: 'Barcode-018',
    bookNo: 'B0118-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Paused',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '19',
    image: 'N/A',
    barcode: 'Barcode-019',
    bookNo: 'B0119-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Paused',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '20',
    image: 'N/A',
    barcode: 'Barcode-020',
    bookNo: 'B0120-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '21',
    image: 'N/A',
    barcode: 'Barcode-021',
    bookNo: 'B0121-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '22',
    image: 'N/A',
    barcode: 'Barcode-022',
    bookNo: 'B0122-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },
  {
    id: '23',
    image: 'N/A',
    barcode: 'Barcode-023',
    bookNo: 'B0123-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '24',
    image: 'N/A',
    barcode: 'Barcode-024',
    bookNo: 'B0124-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },{
    id: '25',
    image: 'N/A',
    barcode: 'Barcode-025',
    bookNo: 'B0125-V01',
    bookName: 'ตะลุยโจทย์ฟิสิกส์เข้าเตรียมอุดมฯ',
    quantity: '5',
    status: 'Active',
    createAt: '10/01/24',
    updateAt: '10/01/24',
    deleteAt: '-',
  },
];

export {columns, statusOptions}
